apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo
  labels:
    app.kubernetes.io/name: bookinfo
    app.kubernetes.io/part-of: pyhookkit
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
